# Generated by Django 4.2.11 on 2024-04-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goleadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_team', models.CharField(max_length=70)),
                ('away_team', models.CharField(max_length=70)),
                ('team', models.CharField(max_length=70)),
                ('scorer', models.CharField(max_length=100)),
                ('minute', models.IntegerField()),
                ('own_goal', models.BooleanField()),
                ('penalty', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_team', models.CharField(max_length=70)),
                ('away_team', models.CharField(max_length=70)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('tournament', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('country', models.CharField(max_length=70)),
                ('neutral', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Penaltis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_team', models.CharField(max_length=70)),
                ('away_team', models.CharField(max_length=70)),
                ('winner', models.CharField(max_length=70)),
                ('first_shooter', models.CharField(max_length=100)),
            ],
        ),
    ]
